---
extends:
  - airbnb
  - prettier
  - plugin:node/recommended
plugins:
  - prettier
parser: babel-eslint
parserOptions:
  sourceType: module
  allowImportExportEverywhere: true
rules:
  prettier/prettier: error
  no-unused-vars: warn
  no-console: "off"
  consistent-return: "off"
  func-names: "off"
  no-process-exit: "off"
  node/no-unsupported-features/es-syntax: "off"
  no-undef: "off"
